[package]
name = "yotona.github.io"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.19.0"
eframe = { version = "0.27.0", features = ["persistence"]}
serde = { version = "1", features = ["derive"]}